'use client'

const SECTIONS = ['Politics', 'Economy', 'Technology', 'Climate', 'Health', 'International', 'Business']
const TRANSPARENCY = [
  'How articles are generated',
  'Sourcing standards',
  'Confidence scoring',
  'Corrections policy',
  'Source transparency log',
]

export default function SiteFooter() {
  return (
    <footer
      style={{
        background: 'var(--black)',
        borderTop: 'var(--border-thick)',
        padding: '3rem 2rem 1.5rem',
        marginTop: '3rem',
      }}
    >
      <div
        style={{
          maxWidth: '100%',
          margin: '0 auto',
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '3rem',
        }}
        className="footer-grid"
      >
        {/* Col 1: Logo + Tagline */}
        <div>
          <div
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '24px',
              fontWeight: 700,
              textTransform: 'uppercase',
              letterSpacing: '-0.03em',
              color: 'var(--white)',
              marginBottom: '12px',
            }}
          >
            THE <span style={{ color: 'var(--orange)' }}>DIS</span>PATCH
          </div>
          <p
            style={{
              fontFamily: 'var(--font-serif)',
              fontSize: '12px',
              lineHeight: 1.7,
              color: 'rgba(255,255,255,0.5)',
              maxWidth: '300px',
            }}
          >
            An autonomous AI editorial system delivering verified, sourced
            journalism with full pipeline transparency. Every article is
            generated, fact-checked, and scored by machine intelligence.
          </p>
        </div>

        {/* Col 2: Sections */}
        <div>
          <div
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '10px',
              fontWeight: 700,
              textTransform: 'uppercase',
              letterSpacing: '0.12em',
              color: 'var(--orange)',
              marginBottom: '16px',
            }}
          >
            Sections
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {SECTIONS.map(section => (
              <a
                key={section}
                href={`/section/${section.toLowerCase()}`}
                style={{
                  fontFamily: 'var(--font-mono)',
                  fontSize: '11px',
                  fontWeight: 700,
                  textTransform: 'uppercase',
                  letterSpacing: '0.06em',
                  color: 'rgba(255,255,255,0.6)',
                  transition: 'color 100ms ease',
                }}
                onMouseEnter={(e) => (e.currentTarget.style.color = 'var(--orange)')}
                onMouseLeave={(e) => (e.currentTarget.style.color = 'rgba(255,255,255,0.6)')}
              >
                {section}
              </a>
            ))}
          </div>
        </div>

        {/* Col 3: Transparency */}
        <div>
          <div
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '10px',
              fontWeight: 700,
              textTransform: 'uppercase',
              letterSpacing: '0.12em',
              color: 'var(--orange)',
              marginBottom: '16px',
            }}
          >
            Pipeline Transparency
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {TRANSPARENCY.map(item => (
              <span
                key={item}
                style={{
                  fontFamily: 'var(--font-mono)',
                  fontSize: '11px',
                  fontWeight: 700,
                  letterSpacing: '0.04em',
                  color: 'rgba(255,255,255,0.45)',
                }}
              >
                {item}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Bottom row */}
      <div
        style={{
          maxWidth: '100%',
          margin: '2.5rem auto 0',
          borderTop: '2px solid rgba(255,255,255,0.1)',
          paddingTop: '1.25rem',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '8px',
        }}
      >
        <span
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '10px',
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: '0.08em',
            color: 'rgba(255,255,255,0.25)',
          }}
        >
          All content autonomously generated by AI · Editorial pipeline powered by Gemini
        </span>
        <span
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '10px',
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: '0.08em',
            color: 'rgba(255,255,255,0.25)',
          }}
        >
          © {new Date().getFullYear()} The Dispatch
        </span>
      </div>

      <style>{`
        @media (max-width: 900px) {
          .footer-grid {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>
    </footer>
  )
}
